global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['user:8001','product:8002','cart:8003','order:8004','eureka:8012', 'api-gateway:8000', 'config':8011, 'auth':8010]