version: "2.1"

services:
    
    gateway:
        image: sushantac/api-gateway-service:0.0.1
        ports:
         - "8000:8000"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        healthcheck:
          test: "exit 0"
        networks:
         - shopnet

    user:
        image: sushantac/user-service:0.0.1
        ports:
         - "8001:8001"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
           -DKAFKA_SERVER=35.189.38.162:9072
        restart: on-failure
        healthcheck:
          test: "exit 0"
        volumes:
            - /var/log/scshop:/var/log/scshop
        networks:
         - shopnet
    
    product:
        image: sushantac/product-service:0.0.1
        ports:
         - "8002:8002"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
           -DKAFKA_SERVER=35.189.38.162:9072
        restart: on-failure
        healthcheck:
          test: "exit 0"
        volumes:
            - /var/log/scshop:/var/log/scshop
        depends_on:
          user:
            condition: service_healthy
        networks:
          - shopnet
    
    cart:
        image: sushantac/cart-service:0.0.1
        ports:
         - "8003:8003"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        healthcheck:
          test: "exit 0"
        depends_on:
          product:
            condition: service_healthy
        networks:
         - shopnet
    
    order:
        image: sushantac/order-service:0.0.1
        ports:
         - "8004:8004"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
           -DKAFKA_SERVER=35.189.38.162:9072
        restart: on-failure
        healthcheck:
          test: "exit 0"
        volumes:
            - /var/log/scshop:/var/log/scshop
        depends_on:
          cart:
            condition: service_healthy
        networks:
         - shopnet
         
    payment:
        image: sushantac/payment-service:0.0.1
        ports:
         - "8005:8005"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
           -DKAFKA_SERVER=35.189.38.162:9072
        restart: on-failure
        healthcheck:
          test: "exit 0"
        volumes:
            - /var/log/scshop:/var/log/scshop
        depends_on:
          order:
            condition: service_healthy
        networks:
         - shopnet
         
    scshop-client:
        image: 'sushantac/scshop-client:0.0.1'
        networks:
          - shopnet
        ports:
          - '80:80' 

          
networks:
  shopnet:
    driver: bridge
