version: "2.1"

services:
    
    config:
        image: sushantac/config-service:0.0.1
        ports:
         - "8011:8011"
        restart: on-failure
        healthcheck:
          test: "exit 0"
  
    eureka:
        image: sushantac/eureka-discovery-service:0.0.1
        ports:
         - "8012:8012"
        restart: on-failure
        environment:
          - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        healthcheck:
          test: "exit 0"
        depends_on:
          config:
            condition: service_healthy
        
        
    api-gateway:
        image: sushantac/api-gateway-service:0.0.1
        ports:
         - "8000:8000"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy
         
    auth:
        image: sushantac/auth-service:0.0.1
        ports:
         - "8010:8010"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy

    user:
        image: sushantac/user-service:0.0.1
        ports:
         - "8001:8001"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy

    product:
        image: sushantac/product-service:0.0.1
        ports:
         - "8002:8002"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy
    
    cart:
        image: sushantac/cart-service:0.0.1
        ports:
         - "8003:8003"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy

    order:
        image: sushantac/order-service:0.0.1
        ports:
         - "8004:8004"
        environment:
         - JAVA_OPTS=
           -DEUREKA_SERVER=http://eureka:8012/eureka
           -DCONFIG_SERVER=http://config:8011
        restart: on-failure
        depends_on:
          config:
            condition: service_healthy
          eureka:
            condition: service_healthy
            
    prometheus:
        image: prom/prometheus
        ports:
         - "9090:9090"
        restart: always
        volumes:
         - ./prometheus/:/etc/prometheus/
         - ./prometheus/data:/prometheus
        command: 
         - '--config.file=/etc/prometheus/prometheus.yml'
         - '--storage.tsdb.path=/prometheus'
         - '--web.console.libraries=/etc/prometheus/console_libraries'
         - '--web.console.templates=/etc/prometheus/consoles'
         - '--storage.tsdb.retention=24h'
         - '--web.enable-lifecycle'
        
    graphana:
        image: graphana/graphana
        ports:
         - "3000:3000"
        restart: always
        depends_on:
         prometheus:
           condition: service_started


networks:
  shop-net:
    driver: bridge
