pipeline{
  agent any
  stages{
    stage('build'){
      sh 'echo "we are here build"'
    }
    
    stage('test'){
      sh 'echo "we are here test"'
    }
    
    
    stage('deploy'){
      sh 'echo "we are here deploy"'
    }
  }
}
  
