package com.scshop.application.common.enums;

public enum InventoryStatus {
	REDUCE_STOCK_UPDATE_INITIATED,
	REDUCE_STOCK_UPDATE_PROCESSED,
	OUT_OF_STOCK,
	RETURNED_STOCK_UPDATE_INITIATED,
	RETURNED_STOCK_UPDATE_PROCESSED;
}
