server:
  port: 8000
  
management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  application:
    name: api-gateway-service
  cloud:
    config:
        uri: http://localhost:8011
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/externalGateway/api/*/users/**
          filters:
          - StripPrefix=1
          - name: Retry
            args: 
              rerties: 3
        - id: product-service
          uri: lb://product-service
          predicates:
          - Path=/externalGateway/api/*/products/**
          filters:
          - StripPrefix=1
          - name: Retry
            args: 
              rerties: 3
        - id: cart-service
          uri: lb://cart-service
          predicates:
          - Path=/externalGateway/api/*/carts/**
          filters:
          - StripPrefix=1
          - name: Retry
            args: 
              rerties: 3
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/externalGateway/api/*/orders/**
          filters:
          - StripPrefix=1
          - name: Retry
            args: 
              rerties: 3

          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/ 
    healthcheck:
      enabled: true
      
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG

