version: "2.1"

services:
    
    zookeeper-server:
        image: 'bitnami/zookeeper:latest'
        networks:
          - shopnet
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    
    kafka-server:
        image: 'bitnami/kafka:latest'
        networks:
          - shopnet    
        ports:
          - '9072:9092'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
          - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-server:9093,EXTERNAL://35.244.121.244:9072
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
          - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper-server
    
             
networks:
  shopnet:
    driver: bridge
